name: auto-invite-ci
services:
  auto-invite:
    build:
      context: docker/app
    volumes:
      - ~/.cache/go/pkg/mod:/go/pkg/mod
      - ./:/
    working_dir: /
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
