version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
