// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSuccessfulInvitationModel = "auto_org_invitation.successful_invitations"

// SuccessfulInvitationModel mapped from table <auto_org_invitation.successful_invitations>
type SuccessfulInvitationModel struct {
	ID               string    `gorm:"column:id;type:uuid;not null" json:"id"`
	OrderID          int64     `gorm:"column:order_id;type:bigint;not null" json:"order_id"`
	GithubUsername   string    `gorm:"column:github_username;type:character varying;not null" json:"github_username"`
	GithubEmail      string    `gorm:"column:github_email;type:character varying;not null" json:"github_email"`
	InvitationStatus string    `gorm:"column:invitation_status;type:invitation_status;not null" json:"invitation_status"`
	SucceededAt      time.Time `gorm:"column:succeeded_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"succeeded_at"`
}

// TableName SuccessfulInvitationModel's table name
func (*SuccessfulInvitationModel) TableName() string {
	return TableNameSuccessfulInvitationModel
}
