// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInvitationModel = "auto_org_invitation.invitations"

// InvitationModel mapped from table <auto_org_invitation.invitations>
type InvitationModel struct {
	ID               string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	OrderID          int64     `gorm:"column:order_id;type:bigint;not null" json:"order_id"`
	GithubUsername   string    `gorm:"column:github_username;type:character varying;not null" json:"github_username"`
	GithubEmail      string    `gorm:"column:github_email;type:character varying;not null" json:"github_email"`
	InvitationStatus string    `gorm:"column:invitation_status;type:invitation_status;not null" json:"invitation_status"`
	FirstError       string    `gorm:"column:first_error;type:jsonb;not null" json:"first_error"`
	CreatedAt        time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:1970-01-01 00:00:00" json:"updated_at"`
}

// TableName InvitationModel's table name
func (*InvitationModel) TableName() string {
	return TableNameInvitationModel
}
