// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFailedInvitationModel = "auto_org_invitation.failed_invitations"

// FailedInvitationModel mapped from table <auto_org_invitation.failed_invitations>
type FailedInvitationModel struct {
	ID               string    `gorm:"column:id;type:uuid;not null" json:"id"`
	OrderID          int64     `gorm:"column:order_id;type:bigint;not null" json:"order_id"`
	GithubUsername   string    `gorm:"column:github_username;type:character varying;not null" json:"github_username"`
	GithubEmail      string    `gorm:"column:github_email;type:character varying;not null" json:"github_email"`
	InvitationStatus string    `gorm:"column:invitation_status;type:invitation_status;not null" json:"invitation_status"`
	FailedAt         time.Time `gorm:"column:failed_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"failed_at"`
}

// TableName FailedInvitationModel's table name
func (*FailedInvitationModel) TableName() string {
	return TableNameFailedInvitationModel
}
